### ISSUE TITLE
can't upload sketch

### ISSUE THREAD

**Issue by TStko93** [anotherAlex154/MeccanoidForArduino#3]
When i upload your sketch i get the following message when i try to compile or upload to my board. Please let me know what I'm doing wrong I'm using an Genunino  no matter what board i keep getting this message-->

Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Uno"

meccanoid_rewrite:9:10: error: Meccanoid.h: No such file or directory

Multiple libraries were found for "Servo.h"
 #include "Meccanoid.h"

 Used: C:\Users\smith\Documents\Arduino\libraries\Servo
          ^~~~~~~~~~~~~

 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries\Servo
compilation terminated.

exit status 1
Meccanoid.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by alexfrederiksen** [comment]
Hmm... is your include statement "#include "Meccanoid.h"" or "#include <Meccanoid.h>" ? I ask because of your output. It should be the latter one, as it is in the meccanoid_test.ino file. Also be sure that the library is in the proper "libraries" folder for the IDE.

**Comment by TStko93** [comment]
I found the issue and got it to work. I have another question is it possible to send commands via bluetooth & how would that be accomplished ?

**Comment by alexfrederiksen** [comment]
Sure, it's not in the scope of this library, but you could connect a bluetooth module to your board and do some research into interfacing with that. I believe there's official support for it.
