### ISSUE TITLE
Adding more chains

### ISSUE THREAD

**Issue by A-A-W** [anotherAlex154/MeccanoidForArduino#4]
Is there a way to add more chains to the code? I want to use more than 4 servo motors, and I have tried numbering the chains (chain.1 chain.2 , chain1 chain2) and nothing works. I don't know much about how to figure this out from the library code.
How do I add a second chain?
Thanks.

**Comment by alexfrederiksen** [comment]
Hi there, yes you should be able have more than 1 chain. Could you post your code?

**Comment by A-A-W** [comment]
#include <Meccanoid.h>

const int chain1pin = 5;
const int chain2pin = 3;
int servo1Stat = 0;
int servo2Stat = 0;
int servo3Stat = 0;
int servo4Stat = 0;


Chain chain(chain1pin);

MeccanoServo servo1 = chain.getServo(0); //first on chain
MeccanoServo servo2 = chain.getServo(1); //second on chain
MeccanoServo servo3 = chain.getServo(2); //3rd on chain
MeccanoServo servo4 = chain.getServo(3); //4th on chain
//MeccanoLed led = chain2.getLed(0); //First on chain (commented out because it is currently unused)

void setup() {
}

void Walk() {
  servo1.setPosition(95);// put leg down
  chain.update();
  delay(200);
  servo2.setPosition(95);// put leg down
  chain.update();
  delay(200);
  servo3.setPosition(85);// put leg down
  chain.update();
  delay(200);
  servo4.setPosition(85);// put leg down
  chain.update();
  delay(200);

  servo4.setPosition(130);// put leg out forwards
  delay(300);
  servo2.setPosition(50);
  delay(300);
  servo1.setPosition(130);
  delay(300);
  servo3.setPosition(50);
  delay(300);

  servo4.setPosition(50);
  delay(1000);
  servo2.setPosition(130);
  delay(1000);
  servo1.setPosition(50);
  delay(1000);
  servo3.setPosition(130);
  delay(1000);
}

void loop() {
  chain.update();
  if (servo1.justConnected()) {
    servo1.setColor(0, 0, 0);
    servo1.setPosition(95);
    delay(200);
    servo1Stat = 1;
  }
  if (servo2.justConnected()) {
    servo2.setColor(0, 0, 0);
    servo2.setPosition(95);
    delay(200);
    servo2Stat = 1;
  }
  if (servo3.justConnected()) {
    servo3.setColor(0, 0, 0);
    servo3.setPosition(85);
    delay(200);
    servo3Stat = 1;
  }
  if (servo4.justConnected()) {
    servo4.setColor(0, 0, 0);
    servo4.setPosition(85);
    delay(200);
    servo4Stat = 1;
  }
  if (led.justConnected()){
     led.setColor(0, 7, 1, 3);
     delay(300);
   }
  delay(500);
  if (servo1Stat == 1) {
    if (servo2Stat == 1) {
      if (servo3Stat == 1) {
        if (servo4Stat == 1) {
          Walk();
          delay(1000);
        }
      }
    }
  }
}

**Comment by alexfrederiksen** [comment]
Hopefully I'm understanding the situation correctly, "Chain" is just a class in c++ (in the library code), so `Chain mychain(chain1pin)` is how we can make a chain called "mychain". Or in your case `Chain chain(chain1pin)` is how you make a chain called "chain". So if you just want another, you can do `Chain chain1(chain1pin)` and `Chain chain2(chain2pin)` to have "chain1" and "chain2" like below. Let me know if it works for you. (:

(also as a side note, I noticed you call chain.update() after setting servo positions. By default, you don't actually need to do this yourself because the library does it automatically for you when setting servo positions and led colors. You still need to have the one chain.update() in your loop() however (; )
``` c++
#include <Meccanoid.h>

const int chain1pin = 5;
const int chain2pin = 3;

int servo1Stat = 0;
int servo2Stat = 0;
int servo3Stat = 0;
int servo4Stat = 0;

Chain chain1(chain1pin);
Chain chain2(chain2pin);

MeccanoServo servo1 = chain1.getServo(0); // first on chain
MeccanoServo servo2 = chain1.getServo(1); // second on chain
MeccanoServo servo3 = chain1.getServo(2); // 3rd on chain
MeccanoServo servo4 = chain1.getServo(3); // 4th on chain
// MeccanoLed led = chain2.getLed(0); //First on chain (commented out because it is currently unused)

// and you could do something like this on chain2
MeccanoServo servo5 = chain2.getServo(0); // first on chain
MeccanoServo servo6 = chain2.getServo(1); // second on chain
MeccanoServo servo7 = chain2.getServo(2); // 3rd on chain
MeccanoServo servo8 = chain2.getServo(3); // 4th on chain

void setup()
{
}

void Walk()
{
    servo1.setPosition(95); // put leg down
    // chain1.update(); library calls this automatically here
    delay(200);
    servo2.setPosition(95); // put leg down
    // chain1.update(); library calls this automatically here
    delay(200);
    servo3.setPosition(85); // put leg down
    // chain1.update(); library calls this automatically here
    delay(200);
    servo4.setPosition(85); // put leg down
    // chain1.update(); library calls this automatically here
    delay(200);

    servo4.setPosition(130); // put leg out forwards
    delay(300);
    servo2.setPosition(50);
    delay(300);
    servo1.setPosition(130);
    delay(300);
    servo3.setPosition(50);
    delay(300);

    servo4.setPosition(50);
    delay(1000);
    servo2.setPosition(130);
    delay(1000);
    servo1.setPosition(50);
    delay(1000);
    servo3.setPosition(130);
    delay(1000);
}

void loop()
{
    chain1.update();

    // and also update chain2
    chain2.update();

    if (servo1.justConnected())
    {
        servo1.setColor(0, 0, 0);
        servo1.setPosition(95);
        delay(200);
        servo1Stat = 1;
    }
    if (servo2.justConnected())
    {
        servo2.setColor(0, 0, 0);
        servo2.setPosition(95);
        delay(200);
        servo2Stat = 1;
    }
    if (servo3.justConnected())
    {
        servo3.setColor(0, 0, 0);
        servo3.setPosition(85);
        delay(200);
        servo3Stat = 1;
    }
    if (servo4.justConnected())
    {
        servo4.setColor(0, 0, 0);
        servo4.setPosition(85);
        delay(200);
        servo4Stat = 1;
    }
    if (led.justConnected())
    {
        led.setColor(0, 7, 1, 3);
        delay(300);
    }

    delay(500);
    if (servo1Stat == 1)
    {
        if (servo2Stat == 1)
        {
            if (servo3Stat == 1)
            {
                if (servo4Stat == 1)
                {
                    Walk();
                    delay(1000);
                }
            }
        }
    }
}

```

**Comment by A-A-W** [comment]
Thank you, it works now.

**Comment by alexfrederiksen** [comment]
No problem (;
